name: 'wsl'

on:
  push:

jobs:

  msys:
      runs-on: windows-latest
      defaults:
        run:
          shell: msys2 {0}
      steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: python-pip
      - uses: actions/checkout@v2
      - run: python -m pip install --progress-bar off pytest
      - run: ./wsl.sh
      - run: python -m pytest -v -s -ra wsl.py --color=yes

  mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-python-pip
    - uses: actions/checkout@v2
    - run: python -m pip install --progress-bar off pytest
    - run: ./wsl.sh
    - run: python -m pytest -v -s -ra wsl.py --color=yes
